OBJS=MonadT.o MonadState.o MonadParser.o MonadControl.o MonadSoln.o MonadContinuation.o StateT.o EndoT.o ContT.o ParserT.o MonadIO.o BacktrT.o Identity.o
INCLUDES=-i../..

include ../../config/make.conf
