OBJS=Templates.o Types.o Headers.o Parser.o Client.o Figo.o Server.o Bookamove.o State.o Demo.o Auth.o
#SYSLIBS=-syslib net -syslib data -syslib posix # -syslib template-haskell
INCLUDES=-i../..

include ../../config/make.conf
