OBJS=Parser.o
SYSLIBS=-syslib data
INCLUDES=-i../..

include ../../config/make.conf
# DO NOT DELETE: Beginning of Haskell dependencies
Parser.o : Parser.hs
Parser.o : ../../Lib/Monad/ParserT.hi
Parser.o : ../../Lib/Monad/MonadParser.hi
# DO NOT DELETE: End of Haskell dependencies
